---
title: "Maps and Visualizations"
output: html_document
date: "2024-07-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(usmap)
library(viridis)
```

#Import Data
```{r Import Data}

models_full <- read_csv("H:/BPHC/OSBO/Data Lab/Enterprise Analytics Team/Projects/10. DOJ Data Challenge/4. Export Data/models_full.csv")
uds_map_state <- read_csv("H:/BPHC/OSBO/Data Lab/Enterprise Analytics Team/Projects/10. DOJ Data Challenge/3. Import Data/UDS/uds_map_state.csv")
states <- read_csv("H:/BPHC/OSBO/Data Lab/Enterprise Analytics Team/Projects/10. DOJ Data Challenge/3. Import Data/states.csv")
```

#Clean UDS Map Data
```{r Remove Territories}

uds_map_state <- uds_map_state[which(uds_map_state$state != 'AS' &
                                       uds_map_state$state != 'FM' & 
                                       uds_map_state$state !=  'GU' & 
                                       uds_map_state$state !=  'MH' & 
                                       uds_map_state$state !=  'MP' & 
                                       uds_map_state$state !=  'PR' & 
                                       uds_map_state$state !=  'PW' & 
                                       uds_map_state$state !=  'VI'), ]
```

#Subset Data into Years
```{r 2015/6 Subsets}

pat_2016 <- models_full %>% 
  subset(year == 2016) %>%
  subset(select = c(state, pat_patients))

opioids_2015 <- models_full %>% 
  subset(year == 2015) %>%
  subset(select = c(state, year, tot_opioids))

deaths_2015 <- models_full %>% 
  subset(year == 2015) %>%
  subset(select = c(state, year, age_adj_rate))
```

```{r 2022 Subsets}

pat_2022 <- models_full %>% 
  subset(year == 2022) %>%
  subset(select = c(state, pat_patients))

opioids_2022 <- models_full %>% 
  subset(year == 2022) %>%
  subset(select = c(state, year, tot_opioids))

deaths_2022 <- models_full %>% 
  subset(year == 2022) %>%
  subset(select = c(state, year, age_adj_rate))
```

```{r Calculate PAT Percent}

uds_map_state_2016 <- subset(uds_map_state, year == 2016)
uds_map_state_2022 <- subset(uds_map_state, year == 2022)

pat_2016 <- merge(pat_2016, uds_map_state_2016, by = 'state')
pat_2022 <- merge(pat_2022, uds_map_state_2022, by = 'state')

pat_2016$pat_per <- round((pat_2016$pat_patients / pat_2016$tot_adult_pats), digits = 4)
pat_2022$pat_per <- round((pat_2022$pat_patients / pat_2022$tot_adult_pats), digits = 4)
```

#Maps
```{r US Map}

us_map <- map_data("state")

states$State <- tolower(states$State)

us_map <- merge(us_map, states, by.x = 'region', by.y = 'State')
```

```{r Format Map Data}

#PAT maps
#merge with state data
pat_map_2016 <- right_join(pat_2016, us_map, by = c('state'= 'Abbreviation'))
pat_map_2022 <- right_join(pat_2022, us_map, by = c('state'= 'Abbreviation'))

#merge years
pat_map <- rbind(pat_map_2016, pat_map_2022)

#Opioid maps
#merge with state data
opioids_map_2015 <- right_join(opioids_2015, us_map, by = c('state'= 'Abbreviation'))
opioids_map_2022 <- right_join(opioids_2022, us_map, by = c('state'= 'Abbreviation'))

#merge years
opioids_map <- rbind(opioids_map_2015, opioids_map_2022)

#Deaths maps
#merge with state data
deaths_map_2015 <- right_join(deaths_2015, us_map, by = c('state'= 'Abbreviation'))
deaths_map_2022 <- right_join(deaths_2022, us_map, by = c('state'= 'Abbreviation'))

#merge years
deaths_map <- rbind(deaths_map_2015, deaths_map_2022)
```

```{r PAT Maps}

pat_map_plot <- ggplot(pat_map, aes(long, lat, fill = pat_per, group = group)) +
  geom_polygon(color = "black") +
  scale_fill_viridis(name = "Percentage of Patients", label = scales::percent) +
  facet_grid(~year) +
  coord_equal() +
  theme_minimal() +
  labs(title = "Percentage of FQHC Patients Who Received \nMedication-Assisted Treatment (MAT) for Opioid Use Disorder",
       caption = "Health Resources and Services Administration, Uniform Data System") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 6),
        legend.position = "bottom",
        legend.box.spacing = unit(15, "pt"),
        plot.caption = element_text(hjust = 0, size = 8),
        plot.margin=grid::unit(c(0,0,0,0), "pt")
        )
```

```{r Opioids Map}

opioids_map_plot <- ggplot(opioids_map, aes(long, lat, fill = tot_opioids, group = group)) +
  geom_polygon(color = "black") +
  scale_fill_viridis(name = "Total Narcotic Analgesics Identified", label = scales::comma) +
  facet_grid(~year) +
  coord_equal() +
  theme_minimal() +
  labs(title = "Total Narcotic Analgesics Identified by NFLIS-Drug Laboratories",
       caption = "U.S. Department of Justice, Drug Enforcement Agency, NFLIS-Drug Public Data") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 6),
        legend.position = "bottom",
        legend.box.spacing = unit(15, "pt"),
        plot.caption = element_text(hjust = 0, size = 8),
        plot.margin=grid::unit(c(0,0,0,0), "pt")
        )
```

```{r Deaths Map}

deaths_map_plot <- ggplot(deaths_map, aes(long, lat, fill = age_adj_rate, group = group)) +
  geom_polygon(color = "black") +
  scale_fill_viridis(name = "Age-Adjusted Death Rate \n(per 100,000)", label = scales::comma) +
  facet_grid(~year) +
  coord_equal() +
  theme_minimal() +
  labs(title = "Deaths Due to Drug Overdose",
       caption = "Centers for Disease Control and Prevention, WONDER, Underlying Cause of Death") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.position = "bottom",
        legend.box.spacing = unit(15, "pt"),
        plot.caption = element_text(hjust = 0, size = 8),
        plot.margin=grid::unit(c(0,0,0,0), "pt")
        )
```

#Export
```{r Export Visualizations}

setwd('H:/BPHC/OSBO/Data Lab/Enterprise Analytics Team/Projects/10. DOJ Data Challenge/4. Export Data')

ggsave("pat_map_plot.png", pat_map_plot, width = 10, height = 4, dpi = 300, units = "in")
ggsave("opioids_map_plot.png", opioids_map_plot, width = 10, height = 4, dpi = 300, units = "in")
ggsave("deaths_map_plot.png", deaths_map_plot, width = 10, height = 4, dpi = 300, units = "in")
```

